# Generated by Django 5.0 on 2023-12-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_calllog_created_at_callrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
